# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs_test

import flatbuffers

class Color(object):
    __slots__ = ['_tab']

    # Color
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Color
    def Red(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Color
    def Green(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # Color
    def Blue(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateColor(builder, red, green, blue):
    builder.Prep(4, 12)
    builder.PrependFloat32(blue)
    builder.PrependFloat32(green)
    builder.PrependFloat32(red)
    return builder.Offset()
