# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs_test

import flatbuffers

class Location(object):
    __slots__ = ['_tab']

    # Location
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Location
    def X(self): return self._tab.Get(flatbuffers.number_types.Int16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Location
    def Y(self): return self._tab.Get(flatbuffers.number_types.Int16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))

def CreateLocation(builder, x, y):
    builder.Prep(2, 4)
    builder.PrependInt16(y)
    builder.PrependInt16(x)
    return builder.Offset()
